apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: hydra-quarkus-4k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hydra-quarkus-4k 
  name: hydra-quarkus-4k
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hydra-quarkus-4k
    weight: 100 
